providers = ['go']

[phases.setup]
nixPkgs = ['...', 'go-migrate']

[phase.build]
cmd = "if [ '$MIGRATE' = 'true' ]; then ./migrate -database 'postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=disable' -path database/migration up; fi"