providers = ['go']

[phases.setup]
nixPkgs = ['...', 'go-migrate']

[phases.start]
cmds = "./migrate -database 'postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=disable' -path database/migration up"