providers = ['go']

[phases.setup]
nixPkgs = ['...', 'curl', 'gnutar', 'coreutils']

[phases.install]
cmds = [
  'curl -L https://github.com/golang-migrate/migrate/releases/download/v3.5.4/migrate.linux-amd64.tar.gz | gnutar xz',
  'chmod +x migrate'
]

[phases.build]
cmds = [
  'go build -o app .'
]

[phases.start]
cmds = [
  'bash -c \'[ "$MIGRATE" = "true" ] && ./migrate -database "postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=disable" -path database/migration up\'',
  './app'
]

